checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths:
    - src/*
    - bin/*

build:
  environment:
    php: '5.6'
  tests:
    override:
      -
        command: 'php vendor/bin/phpunit --coverage-clover=coverage'
        coverage:
          file: coverage
          format: php-clover
